### PR TITLE
Assume the MCs AWSClusterRoleIdentity role

### PR DESCRIPTION
**Pull request by AverageMarcus**
This PR:

- fetches the AWSClusterRoleIdentity of the MC and assumes the role specified in it.

### Testing

Description on how aws-network-topology-operator can be tested.

- [ ] fresh install works
  - [ ] AWS
  - [ ] Azure
  - [ ] KVM
- [ ] upgrade from previous version works
  - [ ] AWS
  - [ ] Azure
  - [ ] KVM

#### Other testing

Description of features to additionally test for aws-network-topology-operator installations.

- [ ] check reconciliation of existing resources after upgrading
- [ ] X still works after upgrade
- [ ] Y is installed correctly

### Checklist

- [ ] Update changelog in CHANGELOG.md.
- [ ] Make sure `values.yaml` and `values.schema.json` are valid.

### CODE REVIEW

**Comment by AverageMarcus** [comment]
@calvix The operator will only run on the MCs and all actions will be done in the MCs AWS account (that's where the TGW will be created). What do you see not working exactly? Maybe I'm missing something.

**Comment by calvix** [comment]
> @calvix The operator will only run on the MCs and all actions will be done in the MCs AWS account (that's where the TGW will be created). What do you see not working exactly? Maybe I'm missing something.

If the WC cluster will be in a different AWS account then you won't be able to attach it to the TGW, its scenario we don't plan for our test environment but it could happen with some customer

**Comment by calvix** [comment]
in general we want to test a scenario where we create clusters in multiple AWSAccount as this is how it works on vintage and customers are used to it, so we will nee dit in the test environment as well, but probably that will be different AWS account without a TGW

**Review by calvix — APPROVED** [review]

**Comment by AverageMarcus** [comment]
Ah gotcha! Yeah, feel like something we can iterate on and add when we need it.

**Pull request merged**
